import React from 'react'
import Navbar from './Navbar'
import about_bg_1 from './Images/about_bg_1.jpeg'
import about_bg_2 from './Images/about_bg_2.jpeg'
import Footer from './Footer'

function MainAbout() {
    return (
        <div style={{ backgroundImage: `url(${about_bg_1})`, backgroundSize: 'cover', backgroundRepeat: 'no-repeat', opacity: "0.9" }}>
            <Navbar />
            <div className='container d-flex flex-column align-items-center justify-content-center' >
                <h1 className='p-4' style={{ fontStyle: "oblique", color: "#ffcc00" }}>ABOUT THE SCHOOL</h1>
                <div className="p-3 mb-4 rounded-3 flex-wrap shadow-lg" style={{ backgroundColor: "#ffffcc" }}>
                    <div className="container-fluid py-3">
                        <h4 className="" style={{ color: "#800000" }}>THE YALE SCHOOL OF ART IS A GRADUATE SCHOOL THAT CONFERS MASTER OF FINE ARTS DEGREES IN GRAPHIC DESIGN, PAINTING/PRINTMAKING, PHOTOGRAPHY, AND SCULPTURE</h4>
                        <p className="">Artists and designers of unusual promise and strong motivation are provided an educational context in which they can explore the potential of their own talents in the midst of an intense critical dialogue. This dialogue is generated by their peers, by distinguished visitors, and by a faculty comprised of professional artists of acknowledged accomplishment.</p>
                        <p>The graduate student’s primary educational experience at Yale is centered on the student’s own studio activity. Supporting this enterprise are the experience, knowledge, and skills gained from rigorous, structured courses such as drawing, filmmaking, the relativity of color, and the rich academic offerings found throughout Yale. Each student is routinely exposed to many aesthetic positions through encounters with faculty members and visitors. The School is devoted not only to the refinement of visual skills, but also to the cultivation of the mind. Students must bring creative force and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.</p>
                        <p className="">The School of Art offers an undergraduate art major for students in Yale College (see the bulletin Yale College Programs of Study). In addition, the School’s courses are open to students in the Graduate School of Arts and Sciences and other professional schools of the University, and School of Art students may enroll in elective courses in the Graduate School and other professional schools as well as in the College with permission.</p>
                    </div>
                </div>
                <div className="p-3 mb-4 rounded-3 flex-wrap shadow-lg" style={{ backgroundColor: "#ffffcc" }}>
                    <div className="container-fluid py-3">
                        <h4 className="" style={{ color: "#800000" }}>MASTER OF FINE ARTS DEGREE (MFAS)</h4>
                        <p className="">The degree of Master of Fine Arts is the only degree offered by the School of Art. It is conferred by the University upon recommendation of the faculty after successful completion of all course work in residence and after a thesis presentation that has been approved by the faculty. It implies distinctive achievement on the part of students in studies in the professional area of their choice and demonstrated capacity for independent work. The minimum residence requirement is two years. All candidates’ work is reviewed by faculty at the end of each term. If the work is not considered satisfactory, the student may not be invited back to complete the program (see section on Review and Awards under Academic Regulations in the chapter General Information). All degree candidates are expected to be present at the Commencement exercises in May unless excused by the dean.</p>
                        <p className=''>Course work for the Master of Fine Arts degree carries a minimum of sixty credits. The disposition of these credits varies according to the area of study and is agreed upon at the time of registration between the student and the student’s faculty adviser.</p>
                    </div>
                </div>
                <div className="p-3 mb-4 rounded-3 flex-wrap shadow-lg" style={{ backgroundColor: "#ffffcc" }}>
                    <div className="container-fluid py-3">
                        <h4 className="" style={{ color: "#800000" }}>PUBLIC LECTURES AND EXHIBITIONS</h4>
                        <p className="">Each department has its own visitors program in which professionals from outside the School are invited to lecture to students or take part in critiques.</p>
                        <p className=''>The School also facilitates a public all-school lecture program, in which ideas of general and cross-disciplinary importance are explored by visiting artists and members of the faculty in events typically hosted in the evening that are free and open to the public.</p>
                        <p className="">The School of Art’s galleries in Green Hall and EIK at 32 Edgewood Avenue provide a year-round forum for the exhibition of work by students, faculty, and special guests in the four graduate departments of the School and the undergraduate program. Green Gallery is open to the public when exhibitions are scheduled, but open hours vary by semester. EIK is open during limited hours for specific exhibitions and events. Please refer to the Gallery & Publications page for more information.</p>
                    </div>
                </div>
            </div>
            <Footer/>
        </div>
    )
}

export default MainAbout
